# Generated by Django 5.2 on 2025-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_headervideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headervideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='headervideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
