# Generated by Django 5.2 on 2025-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_headervideo_options_headervideo_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='Icon name (e.g. Installation, Maintenance)', max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='Video URL', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Image URL', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='services/videos/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='services/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_in_homepage', models.BooleanField(default=False, help_text='Show in homepage (limit 6)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
