# Generated by Django 5.2 on 2025-12-13 16:55

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description with rich text', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Short description for homepage/cards'),
            preserve_default=False,
        ),
    ]
