# Generated by Django 5.2 on 2025-12-13 17:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_service_description_service_long_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Short description for cards')),
                ('long_description', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', null=True)),
                ('price', models.CharField(default='Contact for Quote', help_text='e.g. $100 or Contact for Quote', max_length=50)),
                ('image', models.ImageField(help_text='Main product image', upload_to='products/images/')),
                ('video_url', models.URLField(blank=True, help_text='Video URL', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('features', models.TextField(blank=True, help_text='Comma-separated features e.g. High Efficiency, Durable', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_in_homepage', models.BooleanField(default=False, help_text='Show in homepage (limit 5 for carousel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.subcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
