# Generated by Django 5.2 on 2025-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_subcategory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='Badge text e.g. New Arrival', max_length=50, null=True),
        ),
    ]
