# Generated by Django 5.2 on 2025-12-13 19:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_subcategory_options_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(help_text='Main project image', upload_to='projects/images/')),
                ('description', models.TextField(help_text='Short description')),
                ('long_description', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='Industry/Category e.g. Oil & Gas', max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional video link', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
