# Generated by Django 5.2 on 2025-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(help_text='Type of download e.g. Certificate, Profile, Brochure', max_length=100)),
                ('file', models.FileField(help_text='Upload the document (PDF, etc.)', upload_to='downloads/files/')),
                ('image', models.ImageField(help_text='Thumbnail image for the download', upload_to='downloads/images/')),
                ('description', models.TextField(help_text='Short description content')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
