# Generated by Django 5.2 on 2025-12-14 07:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='requirements',
        ),
        migrations.AddField(
            model_name='career',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
