# Generated by Django 5.2 on 2025-12-14 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_career_requirements_career_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.AddField(
            model_name='navbar',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
