# Generated by Django 5.2 on 2025-12-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_companyinfo_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='show_in_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
